### ISSUE TITLE
Check & request operation missing before using Environment.getExternalStorageDirectory()

### ISSUE THREAD

**Issue by aper-project** [billthefarmer/editor#108]
## Issue description

Hi, in **editor v1.48**, we found a dangerous API usage (https://github.com/billthefarmer/editor/blob/master/src/main/java/org/billthefarmer/editor/Editor.java#L881) which requires **Manifest.permission.WRITE_EXTERNAL_STORAGE** in accordance to the Android official documentation (https://developer.android.com/reference/android/os/Environment?hl=en#getExternalStorageDirectory()).

However, it seems that it missed the _“check”_ and _“request”_ operation in the following call chain starting from the _**Editor.onPrepareOptionsMenu(android.view.Menu)**_ activity if permission is not granted.

```
CALLCHAIN:
	org.billthefarmer.editor.Editor.onPrepareOptionsMenu(android.view.Menu)boolean
	 android.os.Environment.getExternalStorageDirectory()java.io.File
```

This may lead to a SecurityException or related functions unavailable if the user denies the storage permission but still calls the API in this chain,  resulting in bad user experience.

@billthefarmer 
Could you help me review this issue? Thx

**Comment by billthefarmer** [comment]
This has the appearance of possibly being bot generated. The issue is extremely easy to test. Just remove the storage permission and start the app, whereupon it asks for the storage permission. If you accept, it works, if you don't, it appears to work but won't load any files. The recent files menu item still works because `getExternalStorageDirectory()` doesn't require the permission, only if you actually use it to attempt to read a file.
