### ISSUE TITLE
Editor allows opening of some unsupported files

### ISSUE THREAD

**Issue by ziggyone** [billthefarmer/editor#119]
The "open files" window allows me to open unsupported files like .odt .rtf .doc and, oddly enough, some .pdf but not all pdf as seen in the attached screen shot.  When accidentally opening an unsupported file, it hangs and I have to force close Editor.

Editor version 1.50
Android 10
Samsung A10e phone

Thanks.
![Screenshot_Editor](https://user-images.githubusercontent.com/6013324/96291129-3b162d00-0fad-11eb-96f7-c141a63ecbb0.jpg)

**Comment by billthefarmer** [comment]
Because of a number of issues raised by users wanting to open files with weird extensions that android has never heard of, (see closed issues) I have set this dialog to disable media files, application files and too large files, but allow anything else. It is also reliant on android getting the mime type right. Some pdf files can be text files, depending on how they were created. Also users can create files with no or any extension they feel like using at the time.

**Comment by ziggyone** [comment]
Ok, thanks.  The dis-allowed pdf files are all larger than the ones that are allowed, so the size difference explains it.

**Comment by WebworkrNet** [comment]
@billthefarmer As a user, do I have the option to exclude "PDF" as a format? Thank you

**Comment by billthefarmer** [comment]
No, for the above reasons.
