### ISSUE TITLE
Add the editor to "Open with" dialogue

### ISSUE THREAD

**Issue by alexanderadam** [billthefarmer/editor#124]
I wanted to open a Ruby file but [Editor](https://f-droid.org/packages/org.billthefarmer.editor) isn't in the list of applications (I also tried to open a directory but this didn't work neither):

![termux-open projects/website/config.rb   Open with "Krita" "Termux"](https://user-images.githubusercontent.com/372620/111525099-7df74f00-875d-11eb-86e5-9b550aac54c1.png)

**PS:** Thank you for your work! 🙏

**Comment by billthefarmer** [comment]
Android does file association by mime type. See #105, #74, #60, #45.

**Comment by alexanderadam** [comment]
Yes, exactly. I read about that.

So either you would [have to add text files and source code files as association to the `AndroidManifest.xml`](https://richardleggett.com/blog/2013/01/26/registering_for_file_types_in_android/).

Since in this case I wanted to open a Ruby file, this would need at least the MIME type `text/x-ruby` but I guess adding something like `<data android:mimeType="text/*" />` would solve this generically for all text files (not only the `plain` ones).

_If_ editor should be proposed for _any_ file type, you could also simply use `<data android:mimeType="*/*" />` in the manifest and then you could even still match for file extensions with something like `<data android:pathPattern=".*\\.rb" />` (I don't think that matching a file extension would be necessary though).

**Comment by billthefarmer** [comment]
> So you probably would have to add text files and source code files as association to the AndroidManifest.xml.

AndroidManifest.xml:
```xml
      <intent-filter android:scheme="http"
                     tools:ignore="AppLinkUrlError">
        <action android:name="android.intent.action.EDIT" />
        <action android:name="android.intent.action.SEND" />
        <action android:name="android.intent.action.VIEW" />

        <category android:name="android.intent.category.DEFAULT" />
        <data android:mimeType="text/*" />
      </intent-filter>
```
The built in file picker is there for a reason, so that the app can open any file that isn't too big or obviously a media or application binary file without being dependent on what android or any file manager or whatever other app considers to be a text file.

Suspecting that some extensions like '.lua', 'js', '.rb' are being given mime types of 'application/lua' or similar I tested adding `<data android:mimeType="application/*" />` to the app manifest. This causes these files to be loaded immediately without a dialog from a file manager. However it is dangerous because it also causes '.img' and '.apk'  images and app files to be loaded immediately without a dialog from a file manager. Which of course crashes the text editor. So I'm not going to do that.

**Comment by alexanderadam** [comment]
> AndroidManifest.xml

Sorry, you're of course absolutely right. I missed this.
Furthermore Termux claims that the Ruby file is `text/plain`.

So what do you propose? Who's in charge? Is there some corresponding upstream ticket (i.e. on Android) regarding this?

**Comment by billthefarmer** [comment]
I forgot to mention &ndash; there's an app [Intent Intercept](https://f-droid.org/en/packages/de.k3b.android.intentintercept/) on F-Droid that allows you to see what's going on.
