### ISSUE TITLE
Error sd-card saving

### ISSUE THREAD

**Issue by Ygarr** [billthefarmer/editor#130]
Error when saving on sd card storage after editing text file: "open failed: EACCESS (Permission denied)"

But there is permissions for "storage" in App info

**Comment by Ygarr** [comment]
P.S. at least found "... -> Save As..." ->"STORAGE" but..

**Comment by billthefarmer** [comment]
That's a 'feature' of android. If you open a file on an SD card with the built in file picker you will be able to open any file which isn't obviously a media file or an application file or too large. But you probably won't be able to save it unless you use `Save as->Storage`. If you open a file on an SD card using `Open file->Storage`, you should be able to save it, but android won't recognise files with commonly used file extensions as text files. Which is why I wrote the built in file picker because of all the issues raised about file extensions. Now people are raising issues about SD cards.
