### ISSUE TITLE
Error when saving file from another app

### ISSUE THREAD

**Issue by Gitoffthelawn** [billthefarmer/editor#132]
I was using another app, [DAVx5](https://f-droid.org/packages/at.bitfire.davdroid/), and it crashed.  Its debug screen popped up, and I selected the option to load the debug output in your wonderful text editor.  I then tried to save the debug file, but it didn't work.  It gave this error message:

```
Permission Denial: writing androidx.core.content.FileProvider url content://at.bitfire.davdroid.debug/debug/debug-info.txt requires the provider be exported, or grantUriPermission()
```

The device runs Android Nougat and is *not* rooted.

When I open your editor independently, and create a file with a similar name, I have no problem.

BTW, I don't normally have a `Documents` folder, so it has to be created by your editor when saving a new file.  Not sure if that matters.

I'm using v1.57 of your editor.

Thanks.

**Comment by billthefarmer** [comment]
If an app shares something android mandates that it is shared using a content Uri created by a content provider. Editor attempts to resolve content Uris to an actual real file on the device, but is not always successful, but it opens it anyway. If the file is in the app's private folders, which is likely for a debug log file, it won't have write permission, which is exactly what you got.

**Comment by Gitoffthelawn** [comment]
Thanks.  In these cases would it make the most sense to show (1) the real path, (2) a filename with no path (to save in the default folder), or (3) a filename with a default path and allow the save operation to work?

If I understand correctly what its doing and what you wrote (which it's possible I may not), currently Editor shows the wrong path (meaning not the actual file path), but a path that should be valid, yet Editor still can't save the file.  In this case the real path is `debug/filename.txt`, but Editor shows `documents/filename.txt` (which should be valid), but still can't perform the save operation.

I think either showing the real path or allowing a save to the "wrong" path would be better choices than the current behaviour, which simply fails without clearly explaining why.

**Comment by Gitoffthelawn** [comment]
I just noticed that when it fails to save and gives the above error, and I change the filename, Editor will fail again and give the error again.  But if I then use the Save option again, without changing anything, it will suddenly work.  Something's messed up there.

**Comment by billthefarmer** [comment]
The error message shown is provided by android and tells exactly why the file couldn't be saved. In this case it's a share of an entry from my Diary app. The actual path is `/storage/emulated/0/Diary/2021/06/11.md`, which Editor couldn't resolve, but it can't tell it can't save the file until the user presses the **Save** button. In this case the file would be writable by Editor, but because it hasn't resolved the Uri to a file, it isn't:

![Screenshot_20210614-092338 1](https://user-images.githubusercontent.com/3448386/121862402-aeb23a80-ccf2-11eb-8bfe-0107f6f75cb5.png)

Unresolved content Uris are read into the default file, but written back to the original Uri, unless the user uses the **Save as** option. The chances of an app sharing an internal file with write permission are negligible. Why would a developer want to do that? Why would a user want to edit an internal debug log file?

You can't change the filename without using the **Save as** option, which will change the current file.

**Comment by billthefarmer** [comment]
I have attempted to cover all options, but android is a minefield for file access and getting worse in later versions. If a user opens a file using the built in file chooser, no problem unless the file is on an external SD card. If the user opens a file using the **Storage** option, no problem, except for problems with file extensions. If the user opens a file from another app, including a file manager, unless it can resolve the content Uri to a real file, it almost certainly won't have write permission. The solution to this is to use the **Save as** option, either direct or via **Storage** in the case of an external SD card.
