### ISSUE TITLE
FR: Option to open editor in edit mode with keyboard open

### ISSUE THREAD

**Issue by Gitoffthelawn** [billthefarmer/editor#133]
I sometimes use your editor when I want to jot down a quick note.  For this purpose, it would be great if the editor opened in edit mode with the keyboard open.

Would this be possible?

Thanks.

**Comment by billthefarmer** [comment]
I avoid my apps opening with the keyboard open because it is extremely annoying to have to get rid of the keyboard to be able to see what you are looking at, especially on a small device. You have to touch the screen to put the cursor where you want it anyway.

There are two options for opening files for editing rather than viewing, one in the menu **View files**, and the mode line for individual files. See [Mode line](https://github.com/billthefarmer/editor/blob/master/Mode.md).

**Comment by Gitoffthelawn** [comment]
Thanks Bill.  I agree.  I'm only referring to when there is no file loaded or a completely empty file is opened.  In those cases, there is nothing to do besides editing (and no cursor to place), so might as well open the keyboard for the user.

**Comment by billthefarmer** [comment]
There is no code in Editor to make the keyboard appear, only to make it go away when a file is loaded. If you are already editing a file and you press the **New** button, the keyboard doesn't go away. Unless you have empty files dotted about, this is the only circumstance where you get an empty file.

**Comment by Gitoffthelawn** [comment]
I see what you're saying.  I think I largely use Editor in a bit of a different way from you.  The last file I edited is usually no longer available, so when I load Editor from a launcher it always shows a blank page with no keyboard.
