### ISSUE TITLE
Crash when receiving a specific share intent

### ISSUE THREAD

**Issue by opk12** [billthefarmer/editor#152]
I am not interested in this personally, but I thought to mention about a crash.

[OsmAnd](https://github.com/osmandapp/OsmAnd) is a map navigation app based on OpenStreetMap. Sharing the list of Points of Interest ([how-to](https://docs.osmand.net/en/main@latest/osmand/personal/favorites#export--import)) sends an intent (code is [here](https://github.com/osmandapp/OsmAnd/blob/f29edbcbc56d54af71636fe812fdaa1e9b9dc73a/OsmAnd/src/net/osmand/plus/activities/FavoritesTreeFragment.java#L718)) made of

1. the subject `Favorites shared via OsmAnd`
2. the list as plain text:
```
Point of interest 1 - geo:-71.1949,61.817707
...
```
3. the same list as a file in GPX format

This duplication of the list allows an app that does not handle a file to handle the plain text. But the Editor app crashes when it is selected as the share target.

**Comment by billthefarmer** [comment]
When the app receives an intent from another app it [checks for an URI](https://github.com/billthefarmer/editor/blob/c0e5724dc666a751a0509e53d6b2648bbb5fd25f/src/main/java/org/billthefarmer/editor/Editor.java#L518) and attempts to load it. OsmAnd sends a FileProvider URI which breaks the code which attempts to resolve the URI to get the file date so that stuff like the overwrite warning, recent file list, etc, can work. This is fixed in the [latest version](https://github.com/billthefarmer/editor/releases/tag/v1.62), which should be on F-Droid [dreckly](https://en.wiktionary.org/wiki/Dreckly).

**Comment by opk12** [comment]
This is now fixed. Thanks.
