### ISSUE TITLE
Feature Request: Add option to search within file

### ISSUE THREAD

**Issue by doronbehar** [billthefarmer/editor#16]
Sometimes I open very large files with this app and I want to jump to a specific location and a search could be a good option, regular expressions could be a thrill.

BTW, I want you to know that this text editor is the best FOSS option I found on F-Droid and I really like it's style and it's default options and it's customizations.

**Comment by billthefarmer** [comment]
I've just finished implementing search in my Diary app, so it shouldn't be a problem. I'm interested you use it for large files because it's all in memory, and my Nexus 7 chokes on large files. As you can't search the text directly, but must copy it into a string and search the string, that might choke on large files. Regular expressions work very well also.

**Comment by doronbehar** [comment]
That's interesting, opening large files with the app on my device does feel a little bit clungy but I don't mind it too much (I use a 3 years old HTC One M8 with LineageOS nightly).

Can't wait till I'll see it coming, Cheers!

**Comment by billthefarmer** [comment]
I just tried it, it works exactly the same way as my Diary app, but with regular expressions. That will be in the next version.
