### ISSUE TITLE
FDroid install fails

### ISSUE THREAD

**Issue by aplatypus** [billthefarmer/editor#199]
The latest version v1.81 (2/3/2023).

**Comment by billthefarmer** [comment]
If you have installed a ripoff of my app from the play store you will need to uninstall it first. Otherwise what is the error from F-Droid?

**Comment by kamil-cy** [comment]
Hi,

@aplatypus I've just tested all three versions available from https://f-droid.org/packages/org.billthefarmer.editor/ and all of them are fine (I've checked them one by one from 1.82, then 1.82 and finally 1.84). Maybe there is (was?) an issue with the F-droid, but I'm not consider this as an issue anymore since I've checked this on two Android based systems (MIUI and LineageOS).

**Comment by kamil-cy** [comment]
@billthefarmer I can also confirm that latest version 1.85 work fine from F-Droid (again tested on two different android variants), so I guess this issue can be closed, what do you think?
