### ISSUE TITLE
Can't open .js file from termux storage

### ISSUE THREAD

**Issue by hehehe92** [billthefarmer/editor#222]
![Screenshot_20240130-153515_Files](https://github.com/billthefarmer/editor/assets/158172547/8458a0fc-b235-4c94-9226-50b3b6db237c)

**Comment by billthefarmer** [comment]
If you use the storage button in the file open dialog, the request uses the mime type `text/*`, which is a request for any type of text file. Unfortunately, android file managers either use `application/octet-stream`, `application/javascript`, or nothing at all in the case of a Samsung file manager, rather than `text/javascript`, which would be more helpful. You can find out which by using the Intent Intercept app from F-Droid. If it is possible to share a file from Termux, that might be more useful. See #188.

**Comment by hehehe92** [comment]
then xould you add more types?

**Comment by hehehe92** [comment]
if i'm nit mistaken it's here, right?:
https://github.com/billthefarmer/editor/blob/master/src/main/java/org/billthefarmer/editor/OpenFile.java#L271

**Comment by hehehe92** [comment]
i can open it with termux-open, but then i can't save it

**Comment by billthefarmer** [comment]
That's correct, however you can only set one mime type. You can have as many mime types as you like when indicating what sorts of files you can open.

**Comment by hehehe92** [comment]
did you mean you can't?

**Comment by hehehe92** [comment]
can you set it to '*' instead then?

**Comment by billthefarmer** [comment]
You probably won't be able to save a file from Termux because it will probably be in the app's private storage. If you had read the thread I linked to, read the [README,](https://github.com/billthefarmer/editor/blob/master/README.md) or looked at the [closed issues](https://github.com/billthefarmer/editor/issues?q=is%3Aissue+is%3Aclosed) you will see why I'm not changing the mime type.
