### ISSUE TITLE
Always show save icon when file has been modified

### ISSUE THREAD

**Issue by Markus00000** [billthefarmer/editor#34]
In portrait mode, the save icon is not shown even when the file has been modified. I’m not sure if it depends on screen size. The missing icon makes it harder to both know whether a file has been modified and to save it.

Additionally, the save icon is sometimes not shown in landscape mode. How to reproduce:

* Make sure auto-save is enabled.
* Open the default Editor.txt file and empty it.
* Save the file and exit Editor.
* Put phone in portrait mode
* Open Editor
* Click the edit icon
* Write a character into the file
* Put phone in landscape mode
* No save icon is shown, even though the file has unsaved changes
* Add another character
* Now the save icon is shown

**Comment by billthefarmer** [comment]
There is a simple reason for that, it's because of the way android deals with configuration changes (device rotation). Android apps have a sort of three level structure, the top layer is the application which persists as long as the app is in memory. The next layer is the activity - apps may have several but only one is active at any time. The next layer is the views that appear on the screen and the user interacts with.

On a configuration change the activity and all the views are paused, saved and stopped and then restarted and restored. That's how some apps have different configurations on different orientations. The display system uses fancy animations to make it appear to the user that the screen rotated, but it's all an illusion. So the modified file gets saved on rotation if enabled and the save icon disappears.

The guide for developers is [Handling Configuration Changes](https://developer.android.com/guide/topics/resources/runtime-changes.html)

**Comment by Markus00000** [comment]
Well explained, thank you. If I understand correctly, only the question of whether to show the save icon in portrait mode remains?

**Comment by Markus00000** [comment]
The save icon is shown in portrait mode in the newest release. I like that it uses the same space as the open icon because most of the time, one will likely want to save before opening another file. I think this issue can be closed now.
