### ISSUE TITLE
Predictability of top bar icons

### ISSUE THREAD

**Issue by Markus00000** [billthefarmer/editor#35]
I would prefer if the top bar icons were always the same and in the same place. Using icons becomes easier and faster if their position remains unchanged.

* The edit icon is shown if the file is read-only but changes to open when clicked. Afterwards it seems impossible to lock the file again. Opening a file while in read-only mode must be done via the menu.
* The save icon is shown if the file has unsaved changes but hidden otherwise. (It’s also hidden in portrait mode, see #34.)

As space is limited in the top bar, the question is which icons should be shown. A complex solution would be to make it configurable: Let users pick which menu items to display in the top bar.

Alternatively, one could try to estimate how often icons are used and determine which icons carry important information. My guesses:

* When auto-save is disabled, the save icon is likely the most used one. It could also inform users of unsaved changes with a visual hint. Avoiding data loss should be a top priority. *-> show*
* With auto-save enabled, the save icon is likely rarely used. Maybe when a file is synced across devices and waiting for auto save to happen is undesirable. *-> hide*
* The usage of search, open, auto save, word wrap, suggestions, typeface (maybe even text size) will likely vary greatly between users. A user only using one file for notes will rarely use any of these icons, except maybe for search. A user editing both text and code in many different files is more likely to use all of them regularly.

Considering this uncertainty, maybe a menu option that displays a list of possible icons with checkboxes to add them to the top bar is a good solution?

**Comment by billthefarmer** [comment]
I got the idea for icons that only appear when they can do something useful from the text editor that came with the Cyanogenmod File Manager. Adding a search icon has subsequently complicated the issue, especially for small devices. The rules are
* Back - only when started from a file manager or other app
* Search - always appears
* Edit - only when read only
* Open - only if the editor was started from the launcher, not from a file manager
* Save - only when modified - note this and 'edit' effectively occupy the same space as you can't have a modified read only file
Everything else is on the menu.
I should probably change the order so 'edit' and 'save' actually occupy the same space.

**Comment by Markus00000** [comment]
Interesting reasoning. A couple of comments:

* Saving space on smaller devices is a convincing argument for conditionally hiding icons.
* Open: I might have found this to be confusing because I often switch to Editor using the recent apps icon. The Editor state can be a few days old by then and it’s not obvious how I launched it.
* Search: I, for example, have used search maybe twice, so it’s mostly wasted space for me. You probably search more often or it wouldn’t be permanently shown.
* Save/Edit: Let’s assume I scroll through a read-only file, press edit to modify it and want to continue scrolling without activating the keyboard or making accidental edits. I would want to switch back to read-only mode, but the edit icon is gone.

**Comment by billthefarmer** [comment]
I agree the search icon can go on the menu. It is on the toolbar as this appeared to be the convention so that it appears to expand when selected. I don't actually use the app other than for testing updates.

On android 4 the recent apps icon only showed apps that were actually still in memory, I think. Since then it has become another illusion. Apps that were possibly still in memory still appear in recent apps after the device has been shut down, recharged and booted up again. This is obvious with apps like Aldiko, which keep your place in the book you are reading and open back up if still in memory on the same page, but go back to the bookshelf if not, regardless of where it is restarted from.

So if the editor restarts showing the same file in the same position, it was still in memory, if not it wasn't. Also when an app is started by another app is is effectively running in the other app's space, see screen dump.

![screenshot_20171207-143604](https://user-images.githubusercontent.com/3448386/33720518-1b9fe2a0-db5c-11e7-93c8-c05b9bb223a2.png)

Editor is running in OI File Manager's space. So it is exceedingly likely that if you restart the editor from the recent apps you can tell what's going on. If you select a file in a file manager and edit it the expected action is to save it and then go back to the file manager, not open another file. That is why the back icon is in the toolbar and the open icon isn't.

Having yet another icon to switch to read only mode when opening a file already achieves that is just the sort of complexity I am trying to avoid. @arschficken made an apposite comment [here](https://github.com/billthefarmer/editor/issues/6#issuecomment-342312178).

**Comment by Markus00000** [comment]
Reading your explanation, it’s reasonable not to show the open icon in that case.

Regarding the edit icon, I think there are two sensible approaches:

* Fix #36, make it possible to switch between edit and read-only modes and make sure it’s impossible to enter edit mode by accident.
* Remove read-only mode. This closes #36 and reduces complexity.

A broken feature is worse than a missing one and in this case, it gives a false sense of security. If users might unintentionally exit read-only mode just by rotating their device, I think the feature introduces more risk than not having it in the first place.

My preferences are:

* Move search to the menu as you said
* Remove read-only mode for now
* Show the save icon whenever there are unsaved changes (I think I would even show it when auto-save is enabled to make the feature transparent)

Off-topic: I value your wish to keep Editor simple and greatly appreciate your work. It seems as if your idea of making a simple editor collided with it becoming just too good. As stated in the linked comment, Editor seems to have become the favorite editor of many F-Droid users. While this might bring many feature requests, I hope you manage to keep its complexity at a level that isn’t a burden to you.

**Comment by Markus00000** [comment]
This issue can also be closed, right?

I really like being able to toggle edit mode in the new release. Much safer. Sensible icon choice as well.

How you’re handling the save icon now with and without auto-save is excellent, too. It stays in the same place in both cases and allows manual saving even when auto-save is enabled. I find it intuitive and predictable.

**Comment by billthefarmer** [comment]
OK, I'll close it.
