### ISSUE TITLE
Rotating device enters edit mode

### ISSUE THREAD

**Issue by Markus00000** [billthefarmer/editor#36]
How to reproduce:

* Open file so it’s read-only
* Rotate device
* Pencil icon disappears, open icon and cursor appear
* File can be edited

**Comment by billthefarmer** [comment]
This happens for the exact same reasons as #34. The activity and the text view are recreated and the text view is editable by default. The problems I am having with this app is that it started out as a very simple spinoff from another app, see [#30](https://github.com/billthefarmer/editor/issues/30#issuecomment-346934036), but I have received a multitude of enhancement requests since which have made it become extremely complex. I have tried to minimise the complexity by implementing the additional functionality in as simple a manner as possible to try to minimise conflicts between different functions.

**Comment by Markus00000** [comment]
You seem to have fixed this in the newest release. Nice!
