### ISSUE TITLE
Crash when opening empty file

### ISSUE THREAD

**Issue by platypro** [billthefarmer/editor#39]
When opening an empty file with nothing in it to edit, the app crashes.

Version: 1.15 on F-Droid

**Comment by billthefarmer** [comment]
I can't reproduce this. I created a zero length file using `adb shell touch sdcard/empty.text` and tried opening it and modifying it both from the editor and from a file manager. What device and android version are you using?

**Comment by platypro** [comment]
I'm using android 4.4 on a HTC desire 601 using [this](https://f-droid.org/packages/com.simplemobiletools.filemanager/) file manager. I found that using a different file manager seemed to work, just that this one makes the app crash when there is no date modified set on the file (not empty like I first thought).

**Comment by billthefarmer** [comment]
Well that's a good one. That [file manager](https://f-droid.org/packages/com.simplemobiletools.filemanager/) says that a file it created doesn't have a last modified date even though it has (checked with other file managers) and it must keep track of files it created because it sends a Uri  that the file utilities I am using can't resolve and still says the file doesn't have a  last modified date after it has been modified. It sends a resolvable Uri for files it didn't create.
```
content://com.simplemobiletools.filemanager.provider/external_files/emulated/0/Test.txt
content://media/external/file/10793
```
The first Uri above is for the test file the file manager created, the second is the empty file I created for testing earlier. I can trap the exception and prevent the crash, but not resolve the Uri, you just get an empty file with a non-existent path.

**Comment by billthefarmer** [comment]
I have tested a debug version which resolves the Uris from the simplemobiletools file manager. As the app still hasn't been published perhaps you could test it. It may also resolve the problem with Telegram #40.

[Editor-debug.zip](https://github.com/billthefarmer/editor/files/1649861/Editor-debug.zip)

**Comment by platypro** [comment]
Okay. I tested the debug version. It works for me exactly as it does for you. The file now opens without crashing the app, and the logs generated appear approximately the same as yours. I also tried testing other file managers again, and there seems to be no breakage.

```
D/FileUtils File -( 3884): Authority: com.simplemobiletools.filemanager.provider, Fragment: null, Port: -1, Query: null, Scheme: content, Host: com.simplemobiletools.filemanager.provider, Segments: [external_files, storage, emulated, 0, New.txt]
D/FileUtils( 3884): Path /external_files/storage/emulated/0/New.txt
D/FileUtils( 3884): Path /storage/emulated/0/New.txt 
```
