### ISSUE TITLE
[FEATURE REQUEST] Better/proper handling of the TAB character (\t, 0x09)

### ISSUE THREAD

**Issue by ravilov** [billthefarmer/editor#4]
Currently the TAB character is either seemingly ignored (no space between adjacent characters), or shown as what appears as a single space.

**Comment by billthefarmer** [comment]
Well that's a good one. I haven't worried about things like that because you don't appear to be able to enter a tab character on the devices I have. The edit functionality is the standard behaviour of the [EditText](https://developer.android.com/reference/android/widget/EditText.html) widget. Do you mean on entering a tab character or handling tab characters already in a text file? One possibility would be to replace it with 2, 4 or 8 space characters.

**Comment by ravilov** [comment]
My specific case was displaying tabs already in a file but it would be nice to make sure tabs work across the board, in all situations. I didn't know this is a limitation of the standard Android EditText component but I guess that makes sense, this app being just a thin wrapper around that component. Personally I wouldn't like tabs being replaced with spaces. I guess it could work as an disableable option if no better solution is found.

**Comment by billthefarmer** [comment]
I've done some investigation. The EditText component handles tab characters in text inconsistently. If it is at the beginning of a line it is shown as a space larger than a space character, if it is the middle of a line it is shown as a space smaller than a space character. You can copy and paste text with tabs in it and the handling is the same.

I found a [keyboard](https://f-droid.org/packages/org.pocketworkstation.pckeyboard) that can generate tab characters. They and other non printing characters don't get as far as the [onTextChanged()](https://developer.android.com/reference/android/text/TextWatcher.html#onTextChanged(java.lang.CharSequence,%20int,%20int,%20int)) method which is where any special handling would take place.

The problem with tabs is that, except in the Unix/Linux environment, tab handling is not consistent. I've had pull requests on my projects to 'fix' the indenting because I use Emacs to edit my code and it does it consistently with other Unix/Linux tools, but not with Eclipse and Android Studio. It shows correctly on here too, probably because they use Linux tools to do it. Other code editors are just as bad.

As this is supposed to be a simple text editor with no frills, and not a code editor, I don't propose to take this further.
