### ISSUE TITLE
Register for all Extensions

### ISSUE THREAD

**Issue by Himura2la** [billthefarmer/editor#45]
I need an editor for the configs I use in my app. They can be in .yml or .conf or even .my_app_config, why can't I open them? You can exclude known binary extensions if it's possiblr, but please register this app as an editor for all file types

**Comment by billthefarmer** [comment]
It doesn't work like that, it works by mime type. I've got it set to `text/*`, which is any sort of file that contains text. For both accepting a file and opening a file. Android might not recognize the extensions you are using. It seems to depend on which file picker/file manager you use. On my Moto G running 7.1.2 the built in file manager will allow Editor to open .conf files, but not .yml. OI File Manager seems to allow anything.

**Comment by Himura2la** [comment]
Can't it be like `*/*` ? For example, I see OpenKeychain in files with uncommon extensions, maybe we should check how they do it.

**Comment by Himura2la** [comment]
I used to the ES's 'Open as Text' feature, but my new Simple File Manager I found in F-Droid lacks this feature. Maybe I'll try to them also.

**Comment by billthefarmer** [comment]
There doesn't seem to be any consistency with file managers. I've had various issues raised which turned out to be down to file managers. To find out exactly what is going on you can install Intent Intercept. Unfortunately it doesn't show what is returned when an app uses a file picker. The reason the mime type in the app is `text/*` is so users won't corrupt binary files like images and video. The app reads files assuming they are text which will put newline characters in binary files.

Keepass droid uses `*/*` in conjunction with a long list of path patterns looking for `.kdb` and `.kbdx` files. OpenKeychain has a note:

        Association of file types to Keychain
        =====================================
        General remarks about file ending conventions:
        - *.gpg,*.pgp for binary files
        - *.asc for ascii armored files The actual content can be anything.
        The file ending only shows if it is binary or ascii encoded.
        Remarks about the ugly android:pathPattern:
        - We are matching all files with a specific file ending.
        This is done in an ugly way because of Android limitations.
        Read http://stackoverflow.com/questions/1733195/android-intent-filter-for-a-particular-file-extension
        and http://stackoverflow.com/questions/3400072/pathpattern-to-match-file-extension-does-not-work-if-a-period-exists-elsewhere-i/8599921
        for more information.
        - Do _not_ set mimeType for gpg!
        Cyanogenmod's file manager will only show Keychain for gpg files if no mimeType is set!
        For OI Filemanager it makes no difference, gpg files can't be associated

They have also had fun with file managers. They've done the same thing with path patterns.

**Comment by Himura2la** [comment]
OK, I see this was is full of crutches. 

> so users won't corrupt binary files like images and video
One option is to check whether the file is binary (like AkelPad does) of very big before opening.

But I guess it's easier to add "Open as Text" to my file manager.
In this case I won't even need an extra text editor, because the file manager has one integrated
