### ISSUE TITLE
'Enter' hide keyboard instead of entering new line

### ISSUE THREAD

**Issue by mvbasov** [billthefarmer/editor#58]
Thank you again for editor! 
But, unfortunately, i need to create issue. 
To reproduce it i do the following:
- open existing text file
- tap to pencil icon to enter edit mode
- tap to end of any line to place cursor there
- press 'enter' key on virtual keyboard
instead of entering new line virtual keyboard hide.

If I change some settings, rotate screen or switch to another application and then switch back the issue disappeared. 

Issue reproduced on Android 8.1 (LineageOS 15.1 on Xiaomi Mi5s) and Android 6.0.1 (rooted stock firmware on Sony Xperia Z3 Tablet Compact)
I am not totally shure but i think issue was introduced in version 1.24

**Comment by FuzzyWuzzyBMP** [comment]
I also encountered this issue. It does not occur when opening the editor without a file - only when opening an already existing file. Rotating the screen or switching applications makes the issue disappear until next time Editor is opened.

I'm reasonably certain this behavior started with version 1. 24. Reproduced on a LG-H815 (i.e. LG G4), Android 7.1.2, LineageOS 14.1-20171107-NIGHTLY-h815.

P.S.: Thanks for an otherwise excellent editor.

**Comment by arschficken** [comment]
This seems like a return of bug #31, and can be reproduced in the same way: by killing the app and opening it again. As noted, rotating the screen or unchecking and rechecking the Suggestions checkboxes temporarily fix it.

Issue is not present in 1.23.

**Comment by billthefarmer** [comment]
I am currently working on a new version to hopefully fix these issues. Unfortunately the android API makes it relatively easy to make a text view read only and make the keyboard go away, but extremely difficult to switch it back as it was to edit mode without some unforeseen side effects.

**Comment by cubetronic** [comment]
confirmed.
just started experiencing this bug after upgrading from android 7 to 9. i toggle word wrap as a workaround (never thought about toggling suggestions. i always leave that off). i use this app a lot. looking forward to a fix.

**Comment by cubetronic** [comment]
No issue with Gboard.

I switched my Virtual Keyboard to "Gboard" [from Google Play] and this issue is gone. I prefer Gboard so I don't really need a bug fix.

This bug happens with my other keyboards:
Android Keyboard (AOSP) [my default keyboard]
AnySoftKeyboard [from F-Droid]
Simple Keyboard [from F-Droid]

I'm using an Unofficial and Release Candidate Lineage 16 (Android 9) ROM with Gapps Nano.

**Comment by billthefarmer** [comment]
See https://github.com/billthefarmer/editor/issues/56#issuecomment-439029335

**Comment by mvbasov** [comment]
Thanks! v1.25 fix this issue.
