### ISSUE TITLE
"Save as" option missing

### ISSUE THREAD

**Issue by ashwinvis** [billthefarmer/editor#8]
User should be able to alter the path, filename and extension, while creating a new file.

**Comment by billthefarmer** [comment]
See #5. I have since found a very interesting app that includes a 'save as' function - [microMathematics Plus](https://github.com/mkulesh/microMathematics). It uses code apparently out of [Ghost Commander Engine](https://sourceforge.net/projects/ghostcommander), but requires use of the [Android Support Library](https://developer.android.com/topic/libraries/support-library/packages.html).

If I did something similar it would increase the size of this app from about 55Kb to over a megabyte.

**Comment by ashwinvis** [comment]
I didn't know someone else raised this query, apologies.

May be not a full exporer view, but would it cost too much if one could enter the path and filename as text in a small dialog box?

**Comment by billthefarmer** [comment]
Ok, I have added a save as dialog to the menu. New version posted.
