### ISSUE TITLE
Crash with version 1.35 (latest APK as of May 2019)

### ISSUE THREAD

**Issue by clach04** [billthefarmer/editor#83]
I installed https://github.com/billthefarmer/editor/releases/tag/v1.35 on an Android 5.0 device and it crashes once Editor is launched.

Installing https://github.com/billthefarmer/editor/releases/tag/v1.34 works fine.

As there are no apks for 1.37 and 1.36 I've not tested those.

**Comment by billthefarmer** [comment]
Version 1.36, which fixes this bug, is available from the [F-Droid](https://f-droid.org/en) app, but not their [web site](https://f-droid.org/packages/org.billthefarmer.editor) yet, which is why it is not on here yet. The bug is due to Android 4 and 5 not supporting a regex expression, see https://github.com/billthefarmer/editor/issues/73#issuecomment-493149688.

**Comment by clach04** [comment]
Thanks! Installed 1.36 from F-Droid/G-Droid and no crash 😄
