### ISSUE TITLE
Adjustable font size

### ISSUE THREAD

**Issue by Markus00000** [billthefarmer/editor#9]
Being able to adjust the font size would be useful. Especially when using a device with a small screen, I would like to see more of the document than the default font size allows.

**Comment by billthefarmer** [comment]
I have released a new version with a choice of text size and typeface. It should be on F-Droid after a few days.

**Comment by Markus00000** [comment]
Thanks! Two issues:

1) When I select the *small* font size, text becomes gray and loses contrast. However, *medium* and *large* text is black.

2) I understand why providing font size presets may be preferable to a list of font sizes or a text input – especially when the goal is a “simple” editor. That said, I’d benefit from an option smaller than *small.* Maybe four or five sensibly spaced presets would be a compromise between allowing customization and keeping it simple. I think the presets should rise quickly. For example: *tiny (8) – small (10) – medium (16) – large (26) – [extra large (40)]* Alternatively, one could keep three presets and add a *custom* option that allows entering arbitrary font sizes.

**Comment by billthefarmer** [comment]
There is a problem with this. The three text sizes I have chosen are part of the built in styles system and should vary according to the resolution and size of the device they are used on. That is what is available and is what I use in all my apps when I want different text sizes. If you use absolute sizes, it may work just fine on the phones and tablets you test on but not on other devices. The small text is grey due, I think, to antialiasing because the lines are only just over 2 pixels wide on my phone. Larger text is blacker in the middle of the lines.

![screenshot_20170915-161439](https://user-images.githubusercontent.com/3448386/30490725-c0ac75a8-9a32-11e7-9532-73f3bfc8a9af.png)

This is a screenshot on my phone of the same text I used for the image in the README using the small text size. It is grey, but perfectly readable. If it was smaller it would be paler and less readable.

**Comment by Markus00000** [comment]
I’m not convinced that the gray comes from antialiasing.

Larger, gray text in Editor:

![editor](https://user-images.githubusercontent.com/985977/30494158-e5035604-9a3e-11e7-9bb7-07a275c2e612.png)

Smaller, black text in Turbo Editor:

![turbo](https://user-images.githubusercontent.com/985977/30494159-e5268fde-9a3e-11e7-8873-ac6d69c73616.png)

Is it possible that the gray text color comes with the pre-defined style? If you have a look at the section *Colors & contrast,* some styles are lighter, such as *Caption.* Could this apply to your *small* style, too?

https://material.io/guidelines/style/typography.html#typography-other-typographic-guidelines

(I don’t know why our Editor screenshots have gray backgrounds. In the app, the background doesn’t look gray.)

Regarding absolute font sizes, won’t the text area scale automatically depending on the screen? When I compare Turbo Editor on a Moto G (329 ppi) and a Moto Z (535 ppi), the number of characters per line is almost identical when using the same font size.

**Comment by billthefarmer** [comment]
It depends how you specify the font size. In a text view, provided you use the right function the text gets scaled as you say. If you are drawing text in a view, you need to scale it yourself. In my apps I make it a proportion of the view height so it appears in the same proportion on different size screens. The editor background is slightly grey. It looks more so on a web page. I don't change background colours in text views in my apps, they are part of the theme and sometimes have a gradient.

If you use an image editor like Paint.net you can pick colours in an image and get the exact colour. You can also measure things exactly. I will experiment with the text sizes.

**Comment by Markus00000** [comment]
Do you now also think that the gray text color is not caused by anti-aliasing? Maybe that will become obvious when you experiment with the text sizes. Looking forward to it, thanks!

(Background: Thanks for the explanation. I had forgotten that Android introduced background gradients because I can usually barely see them on my phone and some apps override the default theme.)

**Comment by billthefarmer** [comment]
Yes the grey text is due to the styles. I have experimented with text sizes, which gives blacker text. The three styles correspond to 14, 18 and 22 scaled pixels. The scaling factor on my Moto G is 2, if you haven't adjusted it in the Settings app, so the actual pixel sizes are 28, 36 and 44 pixels. The scaling factor on my tablet is ~1.3 so the text appears about the same size.

I have set the three sizes to 12, 18 and 24 scaled pixels.
